# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: gmvazquezsonatype.nexus-iq-azure-extension-debug.nexus-iq-azure-pipeline-task.NexusIqPipelineTask@0
  inputs:
    nexusIqService: 'SonatypeSonatypeApp'
    # organizationId: 'a66808ad6c654fd7bdbbb3216d57b87a'
    applicationId: 'testdata'
    stage: 'Build'
    scanTargets: 'pom.xml, **/*.jar, **/*.war, **/*.ear, **/*.zip, **/*.tar.gz, **'
